### ISSUE TITLE
PARSEME labels to be added to hr500k

### ISSUE THREAD

**Issue by nljubesi** [nljubesi/hr500k#13]
There is the PARSEME dataset, available at https://gitlab.com/parseme/parseme_corpus_hr.

It contains PARSEME:MWE labels that would ideally be present in the hr500k dataset. Except for completeness of hr500k, another argument for the merge is to assure that the PARSEME dataset has the latest linguistic upstream labels.

It does not seem that the sentence IDs are preserved in PARSEME, but we were told that the tokenisation of the PARSEME data has not changed, for that the text attribute should allow for alignment of sentences, and the token ID should allow for PARSEME:MWE labels to be transferred.

@vstefanec can you please check:
1. that we can align the sentences via the text attribute (or, if not, to what extent this is possible)
2. that the label transfer can be done via token IDs (again, if not, to what extent this is possible)

Thank you! <3

**Comment by nljubesi** [comment]
Okay, I did the first steps to ensure that the work is done on time (the non-negotionable deadline is 2023-02-27).

transfer.json has data for 3,635 sentences that can safely be transferred without manual interventions (text is identical, forms in specific token indices are identical as well).

remaining.cupt has the data for the remaining 203 sentences where I think either manual or no transfer is to be performed (text has changed or forms are not at the same index).

@vstefanec let me know by 2023-02-25 1. whether you can insert the transfer.json into the conllup and 2. whether you can transfer any of the remaining 203 sentences manually. I will do at least 1. by myself if you cannot do it (but prefer for you to do everything, of course).

**Comment by vstefanec** [comment]
Annotations are added, @nljubesi .

There was a mismatch with the annotations in one sentence in the transfer-remaining.json file: set.hr-s1786.  These annotations were omitted.

**Comment by nljubesi** [comment]
No sentence left behind! Added manually set.hr-s1786. Thanks, @vstefanec on the quick result!
