### ISSUE TITLE
Check UPOS and features consistency

### ISSUE THREAD

**Issue by tsamardzic** [nljubesi/hr500k#4]
To solve mismatches between deprels and UPOS tags, I sometimes changed UPOS without checking for the features. Make sure all UPOS match their corresponding features

**Comment by nljubesi** [comment]
By features, you mean the UPOS features? Does this mean that I have to identify those tokens for which the attached UPOS features are not listed under the given UPOS tag in our tagset (https://github.com/nljubesi/hr500k/blob/master/mte5-udv2.mapping)? From what I understand, I will not be able to change UPOS features, just to identify those that are not related to the UPOS tag (given our tagset).

**Comment by tsamardzic** [comment]
Exactly, list all cases where the list of features is different from the one defined in our tag set for a given UPOS. For example `UposTag=ADV|Case=Nom|Definite=Ind|Degree=Pos|Gender=Masc|Number=Sing|VerbForm=Part|Voice=Pass`. The features  here correspond to ADJ, not to ADV. If there are such cases, then the UPOS is correct and the features need to be adapted. The adaptation is probably best done manually once the list is available. 

The task should be done the last, that is only after all the other issues are closed.

**Comment by tsamardzic** [comment]
It turns out that we need to solve this before we can move on with some of the other issues (#2 and #6). So closing this issue and open new ones for POS mismatches.
