### ISSUE TITLE
Change mapping?

### ISSUE THREAD

**Issue by tsamardzic** [nljubesi/hr500k#5]
Mapping in both  HR and SR:  `Mdo    ADJ    Form=digit|Type=ordinal    NumType=Ord`

HR annotatiojn:   `UposTag=NUM|NumType=Ord    _`

SR annotation:    `UposTag=ADJ|NumType=Ord    _`

I see no reason why it should be ADJ.

Same for `Mlo.*`

**Comment by tsamardzic** [comment]
Guidelines:

> Numbers vs. Adjectives: In general, cardinal numbers receive the part of speech NUM, while ordinal numbers (more precisely adjectival ordinal numerals) receive the tag ADJ.

So the current mapping should NOT be changed: all `Mdo*` and `Mlo*` should be ADJ. Correct UPOS in HR when there is a conflict.

**Comment by tsamardzic** [comment]
Currently in mt5-udv2.mapping:

`X	_	_	_`
`Xf	_	Type=foreign	_`

Should be:
`X	X	_	_`
`Xf	X	Type=foreign	Foreign=Yes`

There are no other types (Xa, Xe, Xh, Xw) in the current annotation and no UD features corresponding to these types. It might be a good idea to remove them from the mapping.

Still not sure how the current annotation was obtained from these two lines in the mapping.

**Comment by nljubesi** [comment]
Xa, Xe, Xh, Xw should be left for the ReLDI-NormTagNER* datasets

**Comment by tsamardzic** [comment]
Correct  `UposTag=NUM|NumType=Ord _` in Croatian

**Comment by tsamardzic** [comment]
Changed all `NUM` to `ADJ`, and `nummod` to `amod` where XPOS is either Mlo.* or Mdo.
