### ISSUE TITLE
iobj -> obl

### ISSUE THREAD

**Issue by tsamardzic** [nljubesi/hr500k#8]
This is  a v1 to v2 update that didn't take place on the Croatian side because it was not me who did the conversion. 

I spotted the issue while comparing the treebank stats.

**Comment by tsamardzic** [comment]
@nljubesi Is it OK that @vstefanec takes over this task? It's a simple replacement of the string "iobj" with the string "obl". 

It would be good to fix this issue before training new models.

**Comment by vstefanec** [comment]
Sure, no problem, @tsamardzic.
